version: '3'

services:
  service-agent:
    build: ../..
    image: 2060-service-agent
    container_name: chatbot-service-agent
    restart: always
    networks:
      - chatbot
    ports:
      - 2800:3000
      - 2801:3001
    environment:
      - AGENT_PUBLIC_DID=did:web:p2801.ovpndev.2060.io
      - AGENT_ENDPOINT=wss://p2801.ovpndev.2060.io
      - AGENT_INVITATION_IMAGE_URL=https://p2802.ovpndev.2060.io/avatar.png
      - AGENT_LABEL=Chatbot demo dts
      - ANONCREDS_SERVICE_BASE_URL=https://p2801.ovpndev.2060.io
      - USE_CORS=true
      - EVENTS_BASE_URL=https://p2802.ovpndev.2060.io
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=gaia
      - POSTGRES_PASSWORD=2060demo
      - AGENT_WALLET_KEY_DERIVATION_METHOD=ARGON2I_INT
      - AGENT_INVITATION_BASE_URL=https://hologram.zone/
      - REDIS_HOST=redis

  chatbot-dts:
    build: 
      context: ../../
      dockerfile: ./examples/demo-dts/Dockerfile
    image: 2060-chatbot-dts
    container_name: chatbot-dts
    restart: always
    depends_on:
      - service-agent
    networks:
      - chatbot
    ports:
      - 2802:5000
    environment:
      - AGENT_PORT=5000
      - SERVICE_AGENT_ADMIN_URL=https://p2800.ovpndev.2060.io
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=gaia
      - POSTGRES_PASSWORD=2060demo
      - PUBLIC_BASE_URL=https://p2802.ovpndev.2060.io

  redis:
    image: redis:alpine
    restart: always
    networks:
      - chatbot
    ports:
      - 6379:6379
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru

  postgres:
    image: postgres:15.2
    restart: always
    networks:
      - chatbot
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=2060demo
      - POSTGRES_USER=gaia
networks:
  chatbot:
